const  groups =[
            {
                "path":"./ResRoot/ResGroup1908",
                "alias":"数据库",
                "icon":"/images/status/mayor.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                    {
                        "path":"./ResRoot/ResGroup1908/ResGroup115200",
                        "alias":"Mysql",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup1908/ResGroup3600",
                        "alias":"Oracle",
                        "icon":"/images/status/mayor.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup1908/ResGroup3515",
                        "alias":"MSSQL",
                        "icon":"/images/status/mayor.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup1908/ResGroup106245",
                        "alias":"Oracle RAC",
                        "icon":"/images/status/disable.png",
                        "order":0,
                        "child_group":[
                        ]
                    }
                ]
            },
            {
                "path":"./ResRoot/ResGroup3077",
                "alias":"主机设备",
                "icon":"/images/status/mayor.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                    {
                        "path":"./ResRoot/ResGroup3077/ResGroup34484",
                        "alias":"集群主机",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3077/ResGroup25979",
                        "alias":"数据库服务器",
                        "icon":"/images/status/mayor.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3077/ResGroup3455",
                        "alias":"天旦NPM_Linux",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3077/ResGroup34421",
                        "alias":"Linux",
                        "icon":"/images/status/disable.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3077/ResGroup3078",
                        "alias":"Windows",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    }
                ]
            },
            {
                "path":"./ResRoot/ResGroup3083",
                "alias":"应用系统_URL",
                "icon":"/images/status/normal.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                ]
            },
            {
                "path":"./ResRoot/ResGroup3217",
                "alias":"虚拟机",
                "icon":"/images/status/mayor.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                    {
                        "path":"./ResRoot/ResGroup3217/ResGroup34564",
                        "alias":"新疆集群",
                        "icon":"/images/status/mayor.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3217/ResGroup34565",
                        "alias":"预上线集群",
                        "icon":"/images/status/disable.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3217/ResGroup34563",
                        "alias":"三级域集群3_2",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3217/ResGroup34562",
                        "alias":"三级域集群3_1",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3217/ResGroup103756",
                        "alias":"二级域集群2_3",
                        "icon":"/images/status/disable.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3217/ResGroup103755",
                        "alias":"三级域集群3_3",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3217/ResGroup34561",
                        "alias":"二级域集群",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    }
                ]
            },
            {
                "path":"./ResRoot/ResGroup3884",
                "alias":"云计算",
                "icon":"/images/status/normal.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                    {
                        "path":"./ResRoot/ResGroup3884/ResGroup15009",
                        "alias":"新疆集群",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3884/ResGroup34269",
                        "alias":"三级域集群3_2ESX",
                        "icon":"/images/status/disable.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3884/ResGroup34378",
                        "alias":"HANA集群ESX",
                        "icon":"/images/status/disable.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3884/ResGroup15091",
                        "alias":"预上线集群",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3884/ResGroup73404",
                        "alias":"vSphere ESX",
                        "icon":"/images/status/disable.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup3884/ResGroup3885",
                        "alias":"Hyper-v",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                            {
                                "path":"./ResRoot/ResGroup3884/ResGroup3885/ResGroup4023",
                                "alias":"三级域集群3_1",
                                "icon":"/images/status/normal.png",
                                "order":0,
                                "child_group":[
                                ]
                            },
                            {
                                "path":"./ResRoot/ResGroup3884/ResGroup3885/ResGroup4022",
                                "alias":"二级域集群",
                                "icon":"/images/status/normal.png",
                                "order":0,
                                "child_group":[
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                "path":"./ResRoot/ResGroup8333",
                "alias":"4A应用",
                "icon":"/images/status/mayor.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                    {
                        "path":"./ResRoot/ResGroup8333/ResGroup8335",
                        "alias":"URL",
                        "icon":"/images/status/disable.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup8333/ResGroup8487",
                        "alias":"DNS",
                        "icon":"/images/status/mayor.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup8333/ResGroup8334",
                        "alias":"linux主机设备",
                        "icon":"/images/status/mayor.png",
                        "order":0,
                        "child_group":[
                        ]
                    }
                ]
            },
            {
                "path":"./ResRoot/ResGroup22815",
                "alias":"数字档案项目组",
                "icon":"/images/status/normal.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                    {
                        "path":"./ResRoot/ResGroup22815/ResGroup22938",
                        "alias":"虚拟机Linux",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup22815/ResGroup22816",
                        "alias":"主机设备Linux",
                        "icon":"/images/status/normal.png",
                        "order":1,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup22815/ResGroup22817",
                        "alias":"虚拟机WinServer",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    }
                ]
            },
            {
                "path":"./ResRoot/ResGroup34663",
                "alias":"存储与备份",
                "icon":"/images/status/mayor.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                    {
                        "path":"./ResRoot/ResGroup34663/ResGroup110110",
                        "alias":"Netapp 设备",
                        "icon":"/images/status/mayor.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup34663/ResGroup112048",
                        "alias":"HP_3PAR",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    }
                ]
            },
            {
                "path":"./ResRoot/ResGroup35323",
                "alias":"设备URL监控",
                "icon":"/images/status/normal.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                ]
            },
            {
                "path":"./ResRoot/ResGroup105697",
                "alias":"主机",
                "icon":"/images/status/mayor.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                    {
                        "path":"./ResRoot/ResGroup105697/ResGroup105698",
                        "alias":"Linux",
                        "icon":"/images/status/mayor.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup105697/ResGroup116780",
                        "alias":"Mac OS",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    },
                    {
                        "path":"./ResRoot/ResGroup105697/ResGroup106434",
                        "alias":"Windows",
                        "icon":"/images/status/normal.png",
                        "order":0,
                        "child_group":[
                        ]
                    }
                ]
            },
            {
                "path":"./ResRoot/ResGroup105760",
                "alias":"虚拟化",
                "icon":"/images/status/disable.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                    {
                        "path":"./ResRoot/ResGroup105760/ResGroup105761",
                        "alias":"vSphere ESX",
                        "icon":"/images/status/disable.png",
                        "order":0,
                        "child_group":[
                        ]
                    }
                ]
            },
            {
                "path":"./ResRoot/ResGroup106099",
                "alias":"云计算集群",
                "icon":"/images/status/disable.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                ]
            },
            {
                "path":"./ResRoot/ResGroup107604",
                "alias":"其他设备",
                "icon":"/images/status/disable.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                ]
            },
            {
                "path":"./ResRoot/ResGroup117060",
                "alias":"网络设备",
                "icon":"/images/status/disable.png",
                "order":0,
                "type":"ResGroup",
                "child_group":[
                    {
                        "path":"./ResRoot/ResGroup117060/ResGroup117061",
                        "alias":"3Com Bridge",
                        "icon":"/images/status/disable.png",
                        "order":0,
                        "child_group":[
                        ]
                    }
                ]
            }
    ]

export default  groups